## numpy cheatsheet

### Fundamentals of numpy array

In [1]:
import numpy as np

# horizantal line
def br():
    print("")

In [2]:
# Basic 1D array
# default datatype will be int32
arr1 = np.array([2,3,4,5], dtype ='int16')
print(arr1)

br()

# Basic 2D array
arr2 = np.array([[3,5,1,5],[12,5,64,42]])
print(arr2)

[2 3 4 5]

[[ 3  5  1  5]
 [12  5 64 42]]


In [3]:
# Get Dimention
print(arr2.ndim)

br()

# Get Shape
print(arr2.shape)

br()

# Get type
print(arr1.dtype)

2

(2, 4)

int16


In [4]:
# Get size
# item size
print(arr1.itemsize)
print(arr2.itemsize)

br()

# get total size
print(arr1.itemsize * arr1.size)
print(arr2.nbytes)

2
4

8
32


### Data manipulation 

In [5]:
arr1 = np.array([[2,4,6,7,9,7],[1,4,0,9,5,6]])

print(arr1)

br()

# Getting a specific item arr[row:column]
print(arr1[0,2])
print(arr1[-1,-2])

br()

# Getting only row or column
print(arr1[0, :])
print(arr1[: , 3])


[[2 4 6 7 9 7]
 [1 4 0 9 5 6]]

6
5

[2 4 6 7 9 7]
[7 9]


In [6]:
# slicing [start:end:step]
print(arr1[1, 1:-2:2])
print(arr1[::-1, ::-1])

[4 9]
[[6 5 9 0 4 1]
 [7 9 7 6 4 2]]


In [7]:
# changing element
arr1[1,2] = 22
print(arr1)

br()

# changing list of elements
arr1[0, :2:] = [9,8]
arr1[:, 3] = [11,33]
print(arr1)

[[ 2  4  6  7  9  7]
 [ 1  4 22  9  5  6]]

[[ 9  8  6 11  9  7]
 [ 1  4 22 33  5  6]]


In [8]:
# 3d narray
arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr2)

br()

# get spicific element
print(arr2[1,1,0])

br()

# replace
arr2[1,:,1] = [9,9]
print(arr2)
br()

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

7

[[[1 2]
  [3 4]]

 [[5 9]
  [7 9]]]



### Diffrent types of arrays

In [9]:
# All Zeros matrix
arr = np.zeros((2,2))

print(arr)

[[0. 0.]
 [0. 0.]]


In [10]:
%whos

Variable   Type        Data/Info
--------------------------------
arr        ndarray     2x2: 4 elems, type `float64`, 32 bytes
arr1       ndarray     2x6: 12 elems, type `int32`, 48 bytes
arr2       ndarray     2x2x2: 8 elems, type `int32`, 32 bytes
br         function    <function br at 0x000001ED6246F558>
np         module      <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>


In [11]:
# All ones
arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
# Any nummber
arr = np.full((3,3),44)
print(arr)

[[44 44 44]
 [44 44 44]
 [44 44 44]]


In [13]:
# Random numbers
arr = np.random.rand(5,5)

print(arr)

[[0.85972735 0.85300916 0.20773054 0.82937491 0.85402075]
 [0.14989813 0.66143889 0.59941914 0.78228042 0.48555235]
 [0.26356385 0.85776437 0.70930108 0.39714632 0.28741654]
 [0.41416043 0.12080261 0.61066557 0.56626705 0.514258  ]
 [0.6692861  0.61616666 0.69888021 0.8533345  0.10976761]]


In [14]:
# Random Ints


# arr = np.random.randint(start,end,size = (4,4))
arr = np.random.randint(100,size = (4,4))
print(arr)

[[54 76 45 91]
 [84 52 51  3]
 [65 62 40  0]
 [45 28 80 99]]


In [15]:
# Repeat array

arr = np.array([[1,2,3]])
arr1 = np.array([[1,2,3]])

rep = np.repeat(arr,3,axis=0)
rep1 = np.repeat(arr,3,axis=0)

print(rep)

br()

print(rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [16]:
# Create a picture

pic = np.ones((5,5))
fill = np.zeros((3,3))
fill[1][1] = 9


pic[1:-1,1:-1]  = fill     

print(pic)





[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
# Copying arrays

# Donot do like this as it points to the original array
a = np.array([1,2,3])
b = a

# Proper way
a = np.array([1,2,3])
b = a.copy()

## MATHS

In [18]:
arr = np.array([1,2,3,4,5])

# Add
arr + 2
print(arr + 2)
br()

# Sub
arr - 2
print(arr - 2)
br()

# Product
arr * 2
print(arr * 2)
br()

# Div
arr / 2
print(arr // 2)
br()

# Power
arr ** 2
print(arr ** 2)
br()



[3 4 5 6 7]

[-1  0  1  2  3]

[ 2  4  6  8 10]

[0 1 1 2 2]

[ 1  4  9 16 25]



### Linear Algebra

In [22]:
arr = np.ones((2,3))
brr = np.full((3,2),2)

print(arr)
print(brr)

print(np.matmul(arr,brr))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


#### STATS

In [24]:
arr = np.array([[1,2,3],[4,5,6]])

print(np.min(arr))

print(np.max(arr))

1
6


In [25]:
np.sum(arr)

21

### Reorganize

In [31]:
# Verticall stacking
arr = np.ones((2,3))
brr = np.full((2,3),2)

print(np.vstack([arr,brr]))

br()

# Horizantal stacking
print(np.hstack([arr,brr]))

[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]

[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]]
